### ISSUE TITLE
Using the same "GraphQL Type Name"s produces data issues

### ISSUE THREAD

**Issue by alecarg** [wp-graphql/wpgraphql-acf#192]
Hello! First of all, thanks for the great plugin, loving the push.

I found that when setting the same "GraphQL Type Name" for different "Field groups" ie.:
<br/><br/>
<img width="787" alt="Screenshot 2024-03-19 at 05 20 36" src="https://github.com/wp-graphql/wp-graphql-acf/assets/1661802/27852a98-4cd9-4bf1-8346-a9d34df528bf">
(meaning I have many others set as "acf" too)
<br/><br/>
.. then all of a sudden when querying my entity's `acf` property, I seem to get access to all other `acf` properties' from other entities:
<br/><br/>
<img width="368" alt="Screenshot 2024-03-19 at 05 19 38" src="https://github.com/wp-graphql/wp-graphql-acf/assets/1661802/2abc8374-6d10-4bf7-9600-04ae0abc58d7">
<br/><br/>
.. and to prove that those properties aren't in my `rutinas` entity:
<br/><br/>
<img width="643" alt="Screenshot 2024-03-19 at 05 17 46" src="https://github.com/wp-graphql/wp-graphql-acf/assets/1661802/7ac8485b-1171-40c0-8aea-55c1cff39c80">

--

Is this a bug? Or am I misuing the "GraphQL Type Name"? I found it very annoying to have to access the data for each object by specifying the entity name every time. To make things worse, when attempting to "save" data via the REST API (as mutations aren't yet supported), then the field must be named `acf`, hence why I thought I'd kill 2 birds with 1 stone if I just set them all to be `acf` in the first place.

Any ideas on how to fix/improve on the above?

**Comment by jasonbahl** [comment]
> I found it very annoying to have to access the data for each object by specifying the entity name every time

@alecarg this is how GraphQL works. You are explicit about the Types and Fields that you want to consume as an API consumer. 

GraphQL cannot have duplicate Types of the same name, so by assigning multiple ACF Field Groups the type name "acf" it creates a conflict. (Similar to if you tried to register multiple post types with the name "post", you would have issues as well). 

I think the real bug here is that the ACF UI doesn't have validation preventing you from saving a GraphQL field group and assigning it a GraphQL Type Name that already exists. (see: #87)

**Comment by jasonbahl** [comment]
Closing in favor of #87
