### ISSUE TITLE
Inactive field groups used in clone fields not included in schema

### ISSUE THREAD

**Issue by clickbait** [wp-graphql/wpgraphql-acf#45]
### Description

If you use field groups to maintain reusable sets of fields and have these field groups set to inactive, when they are used in clone fields - they are excluded from the schema.

This behaves differently to wp-graphql/wp-graphql-acf - where the cloned fields are included in the schema regardless of whether the parent field group is marked as inactive or not.

### Steps to reproduce

1. Create a new field group.
2. Set that field group as inactive
3. Create a clone field in another field group that includes all of the fields from the first field group.

### WPGraphQL Version

1.14.3

### WPGraphQL For ACF Version

2.0.0-beta.2.3.0

### ACF (Advanced Custom Fields) Version. Free or Pro?

6.1.6 (PRO)

### WordPress Version

6.2.2

### PHP Version

7.4.27

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@clickbait thanks for reporting this. I will look into reproducing and determine if this is something that should change. 

There's definitely a lot of things that are changing intentionally from the previous version.

**Comment by jasonbahl** [comment]
Ok, after more discussion, we will show field groups that are inactive. 

Currently this can be fixed by removing these lines: 

https://github.com/wp-graphql/wpgraphql-acf/blob/main/src/Utils.php#L265-L267

However, if we uncomment these lines, there are side effects. For example, the ACF List Table now shows that each Field Group's "GraphQL Location" is "Post"

This is because inactive field groups are default to the "Post Type  is equal to post" location rule. 

So, we should probably have a way to detect field groups that are both "Active and Show in GraphQL" and another way to detect field groups that "Show in GraphQL" (active or not)
